label: बुकमार्क
flag_short: 'इस आइटम को बुकमार्क करें'
flag_long: 'आप इस आइटम को बुकमार्क कर सकते हैं'
flag_message: 'आपने इस आइटम को बुकमार्क कर लिया है'
unflag_short: 'बुकमार्क हटाएं'
unflag_long: 'आप पहले ही एक बुकमार्क जोड़ चुके हैं'
unflag_message: 'आपने बुकमार्क हटा दिया'
