label: कर्मचारी
description: 'अपनी साइट के साथ सहभागिता करने वाले लोगों को ढूंढें और प्रबंधित करें।'
display:
  default:
    display_options:
      exposed_form:
        options:
          submit_button: फिल्टर
          reset_button_label: Reset
          exposed_sorts_label: 'Sort by'
          sort_desc_label: Desc
      pager:
        options:
          expose:
            items_per_page_label: 'Items per page'
            items_per_page_options_all_label: '- All -'
      fields:
        name:
          label: 'प्रयोक्ता का नाम'
        status:
          label: अवस्था
          settings:
            format_custom_true: सक्रिय
            format_custom_false: बंद
        roles_target_id:
          label: भूमिका
        created:
          label: 'के लिये सदस्य'
        access:
          label: 'अंतिम पहुंच'
        operations:
          label: कार्यवाही
        mail:
          separator: ', '
      filters:
        combine:
          expose:
            label: 'नाम या ईमेल में है'
        status:
          group_info:
            label: अवस्था
            group_items:
              1:
                title: सक्रिय
              2:
                title: बंद
        roles_target_id:
          expose:
            label: भूमिका
        permission:
          expose:
            label: अनुमति
      title: कर्मचारी
      use_more_text: 'और भी'
  page_1:
    display_title: Page
    display_options:
      menu:
        title: सूची
        description: 'अपनी साइट के साथ सहभागिता करने वाले लोगों को ढूंढें और प्रबंधित करें।'
      tab_options:
        title: कर्मचारी
        description: 'उपयोगकर्ता खातों, भूमिकाओं और अनुमतियों का प्रबंधन करें.'
