label: पुरालेख
description: 'सभी सामग्री, महीने के हिसाब से।'
display:
  default:
    display_options:
      title: 'मासिक पुरालेख'
      exposed_form:
        options:
          submit_button: Apply
          reset_button_label: Reset
          exposed_sorts_label: 'Sort by'
          sort_desc_label: Desc
      pager:
        options:
          expose:
            items_per_page_label: 'Items per page'
            items_per_page_options_all_label: '- All -'
          tags:
            previous: ‹‹
            next: ››
      arguments:
        created_year_month:
          title: '{{ arguments.created_year_month }}'
  block_1:
    display_title: ब्लॉक
    display_options:
      arguments:
        created_year_month:
          title: '{{ arguments.created_year_month }}'
  page_1:
    display_title: Page
