label: 'सम्बंधित खबर'
description: 'इस दृश्य का उपयोग पृष्ठों को दिखाने के लिए किया जाता है: समाचारों को वर्गीकृत करें'
display:
  default:
    display_options:
      title: 'सम्बंधित खबर'
      exposed_form:
        options:
          submit_button: लागू
