description: 'हाल के लॉग संदेश'
display:
  default:
    display_options:
      exposed_form:
        options:
          submit_button: फिल्टर
          reset_button_label: Reset
          exposed_sorts_label: 'Sort by'
          sort_desc_label: Desc
      pager:
        options:
          expose:
            items_per_page_label: 'Items per page'
            items_per_page_options_all_label: '- All -'
          tags:
            previous: ‹‹
            next: ››
      fields:
        nothing:
          admin_label: चिन्ह
        severity:
          label: तीव्रता
        type:
          label: प्रकार
        timestamp:
          label: तारीख
        message:
          label: संदेश
          alter:
            alt: '{{ message }}'
        name:
          label: प्रयोक्ता
          separator: ', '
        link:
          label: कार्यवाही
      filters:
        type:
          expose:
            label: प्रकार
        severity:
          expose:
            label: तीव्रता
      title: 'हाल के लॉग संदेश'
      empty:
        area:
          admin_label: 'संदेश लॉग उपलब्ध नहीं हैं'
          content: 'संदेश लॉग उपलब्ध नहीं हैं'
  page:
    display_title: Page
