label: 'कस्टम ब्लॉक पुस्तकालय'
description: 'कस्टम ब्लॉक ढूंढें और प्रबंधित करें।'
display:
  default:
    display_options:
      exposed_form:
        options:
          submit_button: Apply
          reset_button_label: Reset
          exposed_sorts_label: 'Sort by'
          sort_desc_label: Desc
      pager:
        options:
          expose:
            items_per_page_label: 'Items per page'
            items_per_page_options_all_label: '- All -'
      fields:
        info:
          label: 'ब्लॉक की व्याख्या'
          separator: ', '
        type:
          label: 'ब्लॉक प्रकार'
          separator: ', '
        changed:
          label: अद्यतित
        operations:
          label: कार्यवाही
      filters:
        info:
          expose:
            label: 'ब्लॉक की व्याख्या'
        type:
          expose:
            label: 'ब्लॉक प्रकार'
      title: 'कस्टम ब्लॉक पुस्तकालय'
      empty:
        area_text_custom:
          content: 'कोई कस्टम ब्लॉक उपलब्ध नहीं हैं।'
  page_1:
    display_title: Page
    display_options:
      menu:
        title: 'कस्टम ब्लॉक पुस्तकालय'
