label: 'सामग्री खोजें'
description: 'आपकी साइट की सामग्री के माध्यम से खोजने के लिए पूर्व-कॉन्फ़िगर एक खोज पृष्ठ'
display:
  default:
    display_options:
      exposed_form:
        options:
          submit_button: Search
          reset_button_label: Reset
          exposed_sorts_label: 'Sort by'
          sort_desc_label: Desc
      pager:
        options:
          tags:
            previous: '‹ previous'
            next: 'next ›'
          expose:
            items_per_page_label: 'Items per page'
            items_per_page_options_all_label: '- All -'
      filters:
        search_api_fulltext:
          expose:
            label: Search
  page_1:
    display_title: Page
