description: 'हाल की सामग्री।'
display:
  default:
    display_options:
      exposed_form:
        options:
          submit_button: Apply
          reset_button_label: Reset
          exposed_sorts_label: 'Sort by'
          sort_desc_label: Desc
      fields:
        changed:
          separator: ', '
      use_more_text: अधिक
  block_1:
    display_title: ब्लॉक
