label: Frontpage
description: 'All content promoted to the front page.'
display:
  default:
    display_options:
      empty:
        area_text_custom:
          content: 'अब तक कोई प्रथम पृष्ठ सामग्री बनाई नहीं गई है.<br/>का पीछा करो <a target="_blank" href="https://www.drupal.org/docs/user_guide/en/index.html">उपयोगकर्ता गाइड</a> अपनी साइट का निर्माण शुरू करने के लिए।'
        title:
          title: 'आपका स्वागत है [site:name] पे'
      exposed_form:
        options:
          submit_button: Apply
          reset_button_label: Reset
          exposed_sorts_label: 'Sort by'
          sort_desc_label: Desc
      pager:
        options:
          expose:
            items_per_page_label: 'Items per page'
            items_per_page_options_all_label: '- All -'
  feed_1:
    display_title: Feed
  page_1:
    display_title: Page
